{{- if or (and (kindIs "invalid" .Values.jvb.service.enabled) (not .Values.jvb.useHostPort)) .Values.jvb.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jvb.service.type }}
  {{- with .Values.jvb.service.LoadbalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.jvb.UDPPort }}
      {{- if eq .Values.jvb.service.type "NodePort" }}
      nodePort: {{ .Values.jvb.UDPPort }}
      {{- end }}
      protocol: UDP
      name: rtp-udp
    {{- if and .Values.jvb.enableTCP }}
    - port: {{ .Values.jvb.TCPPort }}
      {{- if eq .Values.jvb.service.type "NodePort" }}
      nodePort: {{ .Values.jvb.TCPPort }}
      {{- end }}
      protocol: TCP
      name: rtp-tcp
    - port: 80
      targetPort: httpd
      nodePort: 30080
      protocol: TCP
      name: httpd-tcp
    {{- end }}
  {{- with .Values.jvb.service.externalIPs }}
  externalIPs:
  {{ toYaml . | indent 2 | trim }}
  {{- end }}
  selector:
    {{- include "jitsi-meet.jvb.selectorLabels" . | nindent 4 }}
{{- end }}
